apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-18T21:44:57Z"
  labels:
    run: airflow
  name: airflow
  namespace: default
  resourceVersion: "24554"
  uid: 22dce33d-3800-4b26-a575-f77c09046ceb
spec:
  clusterIP: 10.99.232.207
  clusterIPs:
  - 10.99.232.207
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30816
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: airflow
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
