apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-18T21:42:36Z"
  labels:
    run: airflow
  name: airflow
  namespace: default
  resourceVersion: "24512"
  uid: 85838224-c36d-4e04-a765-dd551f0683da
spec:
  containers:
  - image: puckel/docker-airflow
    imagePullPolicy: Always
    name: airflow
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-csk68
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-csk68
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-18T21:42:38Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-04-18T21:42:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-04-18T21:42:38Z"
    message: 'containers with unready status: [airflow]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-04-18T21:42:38Z"
    message: 'containers with unready status: [airflow]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-04-18T21:42:37Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: puckel/docker-airflow
    imageID: ""
    lastState: {}
    name: airflow
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  phase: Pending
  qosClass: BestEffort
  startTime: "2025-04-18T21:42:38Z"
